apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: secrets-store-csi-driver-ops@anz-bs-openbanking-np-3d6bf4.iam.gserviceaccount.com
  labels:
    app: secrets-store-csi-driver
    app.kubernetes.io/instance: vault-csi
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: secrets-store-csi-driver
    app.kubernetes.io/version: 1.2.4
    helm.sh/chart: secrets-store-csi-driver-1.2.4
  name: secrets-store-csi-driver
  namespace: ops
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    helm.sh/hook: pre-upgrade
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
    helm.sh/hook-weight: "2"
  labels:
    app: secrets-store-csi-driver
    app.kubernetes.io/instance: vault-csi
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: secrets-store-csi-driver
    app.kubernetes.io/version: 1.2.4
    helm.sh/chart: secrets-store-csi-driver-1.2.4
  name: vault-csi-secrets-store-csi-driver-keep-crds
  namespace: ops
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
    helm.sh/hook-weight: "1"
  labels:
    app: secrets-store-csi-driver
    app.kubernetes.io/instance: vault-csi
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: secrets-store-csi-driver
    app.kubernetes.io/version: 1.2.4
    helm.sh/chart: secrets-store-csi-driver-1.2.4
  name: vault-csi-secrets-store-csi-driver-upgrade-crds
  namespace: ops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app: secrets-store-csi-driver
    app.kubernetes.io/instance: vault-csi
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: secrets-store-csi-driver
    app.kubernetes.io/version: 1.2.4
    helm.sh/chart: secrets-store-csi-driver-1.2.4
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  name: secretproviderclasses-admin-role
rules:
- apiGroups:
  - secrets-store.csi.x-k8s.io
  resources:
  - secretproviderclasses
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app: secrets-store-csi-driver
    app.kubernetes.io/instance: vault-csi
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: secrets-store-csi-driver
    app.kubernetes.io/version: 1.2.4
    helm.sh/chart: secrets-store-csi-driver-1.2.4
  name: secretproviderclasses-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - secrets-store.csi.x-k8s.io
  resources:
  - secretproviderclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - secrets-store.csi.x-k8s.io
  resources:
  - secretproviderclasspodstatuses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secrets-store.csi.x-k8s.io
  resources:
  - secretproviderclasspodstatuses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - storage.k8s.io
  resourceNames:
  - secrets-store.csi.k8s.io
  resources:
  - csidrivers
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app: secrets-store-csi-driver
    app.kubernetes.io/instance: vault-csi
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: secrets-store-csi-driver
    app.kubernetes.io/version: 1.2.4
    helm.sh/chart: secrets-store-csi-driver-1.2.4
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: secretproviderclasses-viewer-role
rules:
- apiGroups:
  - secrets-store.csi.x-k8s.io
  resources:
  - secretproviderclasses
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app: secrets-store-csi-driver
    app.kubernetes.io/instance: vault-csi
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: secrets-store-csi-driver
    app.kubernetes.io/version: 1.2.4
    helm.sh/chart: secrets-store-csi-driver-1.2.4
  name: secretprovidersyncing-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    helm.sh/hook: pre-upgrade
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
    helm.sh/hook-weight: "2"
  labels:
    app: secrets-store-csi-driver
    app.kubernetes.io/instance: vault-csi
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: secrets-store-csi-driver
    app.kubernetes.io/version: 1.2.4
    helm.sh/chart: secrets-store-csi-driver-1.2.4
  name: vault-csi-secrets-store-csi-driver-keep-crds
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
    helm.sh/hook-weight: "1"
  labels:
    app: secrets-store-csi-driver
    app.kubernetes.io/instance: vault-csi
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: secrets-store-csi-driver
    app.kubernetes.io/version: 1.2.4
    helm.sh/chart: secrets-store-csi-driver-1.2.4
  name: vault-csi-secrets-store-csi-driver-upgrade-crds
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - create
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: secrets-store-csi-driver
    app.kubernetes.io/instance: vault-csi
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: secrets-store-csi-driver
    app.kubernetes.io/version: 1.2.4
    helm.sh/chart: secrets-store-csi-driver-1.2.4
  name: secretproviderclasses-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secretproviderclasses-role
subjects:
- kind: ServiceAccount
  name: secrets-store-csi-driver
  namespace: ops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: secrets-store-csi-driver
    app.kubernetes.io/instance: vault-csi
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: secrets-store-csi-driver
    app.kubernetes.io/version: 1.2.4
    helm.sh/chart: secrets-store-csi-driver-1.2.4
  name: secretprovidersyncing-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secretprovidersyncing-role
subjects:
- kind: ServiceAccount
  name: secrets-store-csi-driver
  namespace: ops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    helm.sh/hook: pre-upgrade
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
    helm.sh/hook-weight: "2"
  labels:
    app: secrets-store-csi-driver
    app.kubernetes.io/instance: vault-csi
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: secrets-store-csi-driver
    app.kubernetes.io/version: 1.2.4
    helm.sh/chart: secrets-store-csi-driver-1.2.4
  name: vault-csi-secrets-store-csi-driver-keep-crds
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vault-csi-secrets-store-csi-driver-keep-crds
subjects:
- kind: ServiceAccount
  name: vault-csi-secrets-store-csi-driver-keep-crds
  namespace: ops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
    helm.sh/hook-weight: "1"
  labels:
    app: secrets-store-csi-driver
    app.kubernetes.io/instance: vault-csi
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: secrets-store-csi-driver
    app.kubernetes.io/version: 1.2.4
    helm.sh/chart: secrets-store-csi-driver-1.2.4
  name: vault-csi-secrets-store-csi-driver-upgrade-crds
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vault-csi-secrets-store-csi-driver-upgrade-crds
subjects:
- kind: ServiceAccount
  name: vault-csi-secrets-store-csi-driver-upgrade-crds
  namespace: ops
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: secrets-store-csi-driver
    app.kubernetes.io/instance: vault-csi
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: secrets-store-csi-driver
    app.kubernetes.io/version: 1.2.4
    helm.sh/chart: secrets-store-csi-driver-1.2.4
  name: vault-csi-secrets-store-csi-driver
  namespace: ops
spec:
  selector:
    matchLabels:
      app: secrets-store-csi-driver
  template:
    metadata:
      annotations: null
      labels:
        app: secrets-store-csi-driver
        app.kubernetes.io/instance: vault-csi
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: secrets-store-csi-driver
        app.kubernetes.io/version: 1.2.4
        helm.sh/chart: secrets-store-csi-driver-1.2.4
        kubectl.kubernetes.io/default-container: secrets-store
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: NotIn
                values:
                - virtual-kubelet
      containers:
      - args:
        - --v=5
        - --csi-address=/csi/csi.sock
        - --kubelet-registration-path=/var/lib/kubelet/plugins/csi-secrets-store/csi.sock
        image: k8s-gcr.artifactory.gcp.anz/sig-storage/csi-node-driver-registrar:v2.5.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /csi-node-driver-registrar
            - --kubelet-registration-path=/var/lib/kubelet/plugins/csi-secrets-store/csi.sock
            - --mode=kubelet-registration-probe
          initialDelaySeconds: 30
          timeoutSeconds: 15
        name: node-driver-registrar
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 20Mi
        volumeMounts:
        - mountPath: /csi
          name: plugin-dir
        - mountPath: /registration
          name: registration-dir
      - args:
        - --endpoint=$(CSI_ENDPOINT)
        - --nodeid=$(KUBE_NODE_NAME)
        - --provider-volume=/var/run/secrets-store-csi-providers
        - --additional-provider-volume-paths=/etc/kubernetes/secrets-store-csi-providers
        - --metrics-addr=:8095
        - --provider-health-check-interval=2m
        - --max-call-recv-msg-size=4194304
        env:
        - name: CSI_ENDPOINT
          value: unix:///csi/csi.sock
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: k8s-gcr.artifactory.gcp.anz/csi-secrets-store/driver:v1.2.4
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /healthz
            port: healthz
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 10
        name: secrets-store
        ports:
        - containerPort: 9808
          name: healthz
          protocol: TCP
        - containerPort: 8095
          name: metrics
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 100Mi
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /csi
          name: plugin-dir
        - mountPath: /var/lib/kubelet/pods
          mountPropagation: Bidirectional
          name: mountpoint-dir
        - mountPath: /var/run/secrets-store-csi-providers
          name: providers-dir
        - mountPath: /etc/kubernetes/secrets-store-csi-providers
          name: providers-dir-0
      - args:
        - --csi-address=/csi/csi.sock
        - --probe-timeout=3s
        - --http-endpoint=0.0.0.0:9808
        - -v=2
        image: k8s-gcr.artifactory.gcp.anz/sig-storage/livenessprobe:v2.7.0
        imagePullPolicy: IfNotPresent
        name: liveness-probe
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 20Mi
        volumeMounts:
        - mountPath: /csi
          name: plugin-dir
      imagePullSecrets:
      - name: artifactory-robot-account
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: secrets-store-csi-driver
      volumes:
      - hostPath:
          path: /var/lib/kubelet/pods
          type: DirectoryOrCreate
        name: mountpoint-dir
      - hostPath:
          path: /var/lib/kubelet/plugins_registry/
          type: Directory
        name: registration-dir
      - hostPath:
          path: /var/lib/kubelet/plugins/csi-secrets-store/
          type: DirectoryOrCreate
        name: plugin-dir
      - hostPath:
          path: /var/run/secrets-store-csi-providers
          type: DirectoryOrCreate
        name: providers-dir
      - hostPath:
          path: /etc/kubernetes/secrets-store-csi-providers
          type: DirectoryOrCreate
        name: providers-dir-0
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: pre-upgrade
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
    helm.sh/hook-weight: "20"
  labels:
    app: secrets-store-csi-driver
    app.kubernetes.io/instance: vault-csi
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: secrets-store-csi-driver
    app.kubernetes.io/version: 1.2.4
    helm.sh/chart: secrets-store-csi-driver-1.2.4
  name: secrets-store-csi-driver-keep-crds
  namespace: ops
spec:
  backoffLimit: 0
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      name: vault-csi-secrets-store-csi-driver-keep-crds
    spec:
      containers:
      - args:
        - patch
        - crd
        - secretproviderclasses.secrets-store.csi.x-k8s.io
        - secretproviderclasspodstatuses.secrets-store.csi.x-k8s.io
        - -p
        - '{"metadata":{"annotations": {"helm.sh/resource-policy": "keep"}}}'
        image: k8s-gcr.artifactory.gcp.anz:443/csi-secrets-store/driver-crds:v1.2.4
        imagePullPolicy: IfNotPresent
        name: crds-keep
      imagePullSecrets:
      - name: artifactory-robot-account
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Never
      serviceAccountName: vault-csi-secrets-store-csi-driver-keep-crds
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
    helm.sh/hook-weight: "10"
  labels:
    app: secrets-store-csi-driver
    app.kubernetes.io/instance: vault-csi
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: secrets-store-csi-driver
    app.kubernetes.io/version: 1.2.4
    helm.sh/chart: secrets-store-csi-driver-1.2.4
  name: secrets-store-csi-driver-upgrade-crds
  namespace: ops
spec:
  backoffLimit: 0
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      name: vault-csi-secrets-store-csi-driver-upgrade-crds
    spec:
      containers:
      - args:
        - apply
        - -f
        - crds/
        image: k8s-gcr.artifactory.gcp.anz:443/csi-secrets-store/driver-crds:v1.2.4
        imagePullPolicy: IfNotPresent
        name: crds-upgrade
      imagePullSecrets:
      - name: artifactory-robot-account
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Never
      serviceAccountName: vault-csi-secrets-store-csi-driver-upgrade-crds
---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  labels:
    app: secrets-store-csi-driver
    app.kubernetes.io/instance: vault-csi
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: secrets-store-csi-driver
    app.kubernetes.io/version: 1.2.4
    helm.sh/chart: secrets-store-csi-driver-1.2.4
  name: secrets-store.csi.k8s.io
spec:
  attachRequired: false
  podInfoOnMount: true
  volumeLifecycleModes:
  - Ephemeral